[build]
  command = "cd invoice-app && pnpm install --frozen-lockfile && pnpm run build"
  publish = "invoice-app/dist"
  functions = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--package-manager=pnpm"
  NODE_VERSION = "22.20.0" 
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL"
  NPM_CONFIG_IGNORE_SCRIPTS = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
  